export interface TrigramInfo {
  name: string;
  hanja: string;
  symbol: string;
  nature: string;
  element: string;
  family: string;
  lines: ('yin' | 'yang')[]; // bottom to top (3 lines)
}

export const EIGHT_TRIGRAMS: Record<string, TrigramInfo> = {
  건: { name: '건', hanja: '乾', symbol: '☰', nature: '하늘(天)', element: '금(金)', family: '아버지', lines: ['yang', 'yang', 'yang'] },
  태: { name: '태', hanja: '兌', symbol: '☱', nature: '연못(澤)', element: '금(金)', family: '소녀(막내딸)', lines: ['yang', 'yang', 'yin'] },
  리: { name: '리', hanja: '離', symbol: '☲', nature: '불(火)', element: '화(火)', family: '중녀(둘째딸)', lines: ['yang', 'yin', 'yang'] },
  진: { name: '진', hanja: '震', symbol: '☳', nature: '우레(雷)', element: '목(木)', family: '장남(큰아들)', lines: ['yang', 'yin', 'yin'] },
  손: { name: '손', hanja: '巽', symbol: '☴', nature: '바람(風)', element: '목(木)', family: '장녀(큰딸)', lines: ['yin', 'yang', 'yang'] },
  감: { name: '감', hanja: '坎', symbol: '☵', nature: '물(水)', element: '수(水)', family: '중남(둘째아들)', lines: ['yin', 'yang', 'yin'] },
  간: { name: '간', hanja: '艮', symbol: '☶', nature: '산(山)', element: '토(土)', family: '소남(막내아들)', lines: ['yin', 'yin', 'yang'] },
  곤: { name: '곤', hanja: '坤', symbol: '☷', nature: '땅(地)', element: '토(土)', family: '어머니', lines: ['yin', 'yin', 'yin'] },
};

export interface HexagramData {
  num: number;
  nameKr: string;
  nameHanja: string;
  upperKey: keyof typeof EIGHT_TRIGRAMS;
  lowerKey: keyof typeof EIGHT_TRIGRAMS;
  symbolMeaning: string;
  judgment: string;
  imageAdvice: string;
  score: number;
  grade: '대길(大吉)' | '길(吉)' | '평(平)' | '주의(注意)' | '험(險)';
  actionGuidance: string;
  fortuneAspects: {
    wealth: string;
    career: string;
    love: string;
    health: string;
  };
}

export const ICHING_64_DATABASE: HexagramData[] = [
  {
    num: 1,
    nameKr: '건위천(乾爲天)',
    nameHanja: '乾',
    upperKey: '건',
    lowerKey: '건',
    symbolMeaning: '하늘 위에 또 하늘이 있어 순양(純陽)의 위대한 창조 에너지가 가득함',
    judgment: '원형이정(元亨利貞) - 지극히 크고 바른 도리로 나아가니 크게 형통하고 모든 일이 성취됩니다.',
    imageAdvice: '하늘의 운행이 건실하니, 군자는 스스로 힘써 쉬지 않고 도약하며 덕을 쌓습니다.',
    score: 98,
    grade: '대길(大吉)',
    actionGuidance: '강력한 리더십과 추진력으로 큰 뜻을 펼치기에 최상의 때입니다. 오만함만 경계하십시오.',
    fortuneAspects: {
      wealth: '막대한 자금 회전과 대규모 투자 기회가 활짝 열립니다.',
      career: '승진, 공직 등용, 시험 합격, 최고 책임자로 추대되는 영예가 따릅니다.',
      love: '당당하고 매력적인 이상형을 만나며 주도적인 연애가 펼쳐집니다.',
      health: '기혈이 왕성하나 두통이나 과로로 인한 피로를 주의하세요.',
    },
  },
  {
    num: 2,
    nameKr: '곤위지(坤爲地)',
    nameHanja: '坤',
    upperKey: '곤',
    lowerKey: '곤',
    symbolMeaning: '대지 위에 대지가 있어 만물을 온유하게 품고 기르는 순음(純陰)의 덕성',
    judgment: '선하면 헤매고 후하면 얻으리니, 앞장서기보다 유순하게 따를 때 비로소 큰 복을 누립니다.',
    imageAdvice: '지세가 두텁고 넓으니, 군자는 덕을 두텁게 쌓아 만물을 포용합니다.',
    score: 92,
    grade: '길(吉)',
    actionGuidance: '참모나 조력자로서 내실을 다지고 겸손하게 협력할 때 막대한 이익을 거둡니다.',
    fortuneAspects: {
      wealth: '부동산이나 저축, 장기 투자를 통해 재산이 탄탄하게 불어납니다.',
      career: '윗사람이나 파트너의 전폭적인 신뢰를 얻어 안정적인 지위를 확보합니다.',
      love: '포용력 있는 배려와 다정함으로 깊은 신뢰와 화합을 다집니다.',
      health: '소화기 계통과 위장을 편안하게 다스리고 따뜻한 음식을 드세요.',
    },
  },
  {
    num: 3,
    nameKr: '수뢰둔(水雷屯)',
    nameHanja: '屯',
    upperKey: '감',
    lowerKey: '진',
    symbolMeaning: '구름과 번개가 엉켜 대지 위로 싹을 틔우기 직전의 험난한 창업기',
    judgment: '어려움 속에서 새 생명이 잉태되니, 경솔하게 나아가지 말고 후견인을 세워 힘을 기르라.',
    imageAdvice: '구름과 우레가 엉킨 상이니, 군자는 질서를 세우고 안정을 도모합니다.',
    score: 72,
    grade: '주의(注意)',
    actionGuidance: '씨앗이 단단한 땅을 뚫고 나오는 시기입니다. 조급증을 버리고 차분히 준비하세요.',
    fortuneAspects: {
      wealth: '초기 비용 지출이 많으니 자금 관리에 신중하고 무리한 투자를 삼가세요.',
      career: '창업이나 신규 프로젝트 초기의 혼선을 겪으나 곧 기반이 잡힙니다.',
      love: '서로를 알아가는 과정에서 오해가 생길 수 있으니 솔직한 대화가 필요합니다.',
      health: '체력 저하와 초기 감기, 신경성 스트레스를 잘 돌보세요.',
    },
  },
  {
    num: 4,
    nameKr: '산수몽(山水蒙)',
    nameHanja: '蒙',
    upperKey: '간',
    lowerKey: '감',
    symbolMeaning: '산기슭 아래 안개가 자욱하여 샘물이 길을 찾는 어린아이의 배움의 상',
    judgment: '내가 어린이를 찾는 것이 아니라 어린이가 나를 찾아 배우니, 성실하게 물으면 형통하리라.',
    imageAdvice: '산 아래 샘물이 솟으니, 군자는 행동을 과감히 하고 덕을 길러냅니다.',
    score: 76,
    grade: '평(平)',
    actionGuidance: '자만하지 말고 전문가나 스승의 가르침을 겸손히 구하면 지혜의 눈이 뜨입니다.',
    fortuneAspects: {
      wealth: '공부와 배움에 투자하는 것이 가장 확실한 미래의 부를 부릅니다.',
      career: '자격증 취득, 교육, 연수, 신규 분야 습득에 대단히 유리합니다.',
      love: '순수하고 풋풋한 인연이 시작될 수 있으나 성급한 결단은 금물입니다.',
      health: '시력 감퇴나 뇌 피로를 조심하고 충분한 수면을 취하세요.',
    },
  },
  {
    num: 5,
    nameKr: '수천수(水天需)',
    nameHanja: '需',
    upperKey: '감',
    lowerKey: '건',
    symbolMeaning: '하늘 위에 구름비가 가득하여 비가 내릴 때를 기다리며 때를 기다림',
    judgment: '믿음을 가지고 때를 기다리면 크게 형통하고, 큰 내를 건너는 데 이롭습니다.',
    imageAdvice: '구름이 하늘에 오르니, 군자는 음식을 즐기며 편안하게 때를 기다립니다.',
    score: 86,
    grade: '길(吉)',
    actionGuidance: '조급하게 덤비지 말고 실력을 비축하며 여유를 즐기세요. 곧 기회의 단비가 내립니다.',
    fortuneAspects: {
      wealth: '자금이 묶여 있는 듯하나 때가 되면 큰 이익으로 돌아옵니다.',
      career: '승진이나 이직 발표를 앞두고 있다면 느긋하게 기다리는 자가 승리합니다.',
      love: '서두르지 않고 자연스러운 흐름에 맡기면 좋은 결실을 맺습니다.',
      health: '규칙적인 식습관과 여유로운 휴식이 최고의 보약입니다.',
    },
  },
  {
    num: 6,
    nameKr: '천수송(天水訟)',
    nameHanja: '訟',
    upperKey: '건',
    lowerKey: '감',
    symbolMeaning: '하늘은 위로 가고 물은 아래로 흘러 뜻이 어긋나 시비와 송사가 일어남',
    judgment: '신의가 있어도 막히니 삼가고 두려워하여 중간에 멈추면 길하고 끝까지 다투면 흉하다.',
    imageAdvice: '하늘과 물이 거스르니, 군자는 일을 시작할 때 미리 명확히 도모합니다.',
    score: 65,
    grade: '험(險)',
    actionGuidance: '소송이나 다툼은 양쪽 모두에게 상처를 줍니다. 조기에 타협하고 양보하세요.',
    fortuneAspects: {
      wealth: '금전 거래 시 계약서를 꼼꼼히 확인하고 법적 분쟁을 사전에 피하세요.',
      career: '직장 내 동료나 거래처와의 마찰을 피하고 중재자의 조언을 구하세요.',
      love: '자존심 싸움으로 관계가 틀어질 수 있으니 한 걸음 물러서십시오.',
      health: '화병, 스트레스로 인한 혈압 상승과 불면증을 다스리세요.',
    },
  },
  {
    num: 7,
    nameKr: '지수사(地水師)',
    nameHanja: '師',
    upperKey: '곤',
    lowerKey: '감',
    symbolMeaning: '땅속에 모인 수많은 지하수처럼 군사를 통솔하여 출진하는 장수의 상',
    judgment: '바르고 정당한 명분으로 군사를 이끄는 백전노장이어야 허물이 없으리라.',
    imageAdvice: '땅속에 물이 모여 있듯, 군자는 백성을 아끼고 무리를 잘 결속합니다.',
    score: 84,
    grade: '길(吉)',
    actionGuidance: '엄격한 기강과 공정한 규칙으로 팀을 이끄세요. 승리는 준비된 자의 것입니다.',
    fortuneAspects: {
      wealth: '목적의식이 뚜렷한 대규모 사업 자금 집행에 유리합니다.',
      career: '조직 개편, 팀장 부임, 프로젝트 리더로서 통솔력을 입증합니다.',
      love: '상대방을 통제하려 하지 말고 든든한 보호자가 되어주세요.',
      health: '체력 관리에 힘쓰고 관절과 허리 건강을 보살피세요.',
    },
  },
  {
    num: 8,
    nameKr: '수지비(水地比)',
    nameHanja: '比',
    upperKey: '감',
    lowerKey: '곤',
    symbolMeaning: '물이 땅 위를 촉촉이 적시며 하나로 친밀하게 융화되는 화합의 상',
    judgment: '서로 친하여 돕고 결속하니 길하리라. 늦게 오는 자는 흉하리니 때를 놓치지 말라.',
    imageAdvice: '땅 위에 물이 있으니, 군자는 여러 사람과 친교를 맺고 화목합니다.',
    score: 94,
    grade: '대길(大吉)',
    actionGuidance: '진심으로 사람들과 교류하고 협력하세요. 뜻을 같이할 평생의 동지를 얻습니다.',
    fortuneAspects: {
      wealth: '동업, 공동 투자, 협동조합 등 연대할 때 재물이 크게 늘어납니다.',
      career: '인맥의 지원을 받아 추천이나 스카우트 제의를 받게 됩니다.',
      love: '천생연분의 따뜻한 인연을 만나 마음이 깊게 통하는 대길한 애정운입니다.',
      health: '혈액순환이 원활해지고 심신이 안락해집니다.',
    },
  },
  {
    num: 9,
    nameKr: '풍천소축(風天小畜)',
    nameHanja: '小畜',
    upperKey: '손',
    lowerKey: '건',
    symbolMeaning: '하늘 위에 바람이 불어 구름이 모이나 아직 비가 내리지 않는 작은 축적',
    judgment: '서쪽 교외에 빽빽한 구름만 일고 아직 비는 내리지 않으니, 작은 힘을 저축하라.',
    imageAdvice: '바람이 하늘 위로 부니, 군자는 문채를 가다듬고 덕을 닦습니다.',
    score: 82,
    grade: '평(平)',
    actionGuidance: '큰 승부를 걸기엔 아직 여건이 무르익지 않았습니다. 차분히 실력과 자금을 저축하세요.',
    fortuneAspects: {
      wealth: '작은 돈을 아끼고 절약하여 시드머니를 단단히 모을 때입니다.',
      career: '조용히 실무 역량을 기르고 포트폴리오를 완벽하게 보완하세요.',
      love: '잔잔한 호감은 있으나 결실을 맺기까지는 인내가 더 필요합니다.',
      health: '호흡기 관리와 환기에 신경 쓰고 가벼운 유산소 운동을 하세요.',
    },
  },
  {
    num: 10,
    nameKr: '천택리(天澤履)',
    nameHanja: '履',
    upperKey: '건',
    lowerKey: '태',
    symbolMeaning: '호랑이 꼬리를 밟았으나 예의와 침착함으로 물리지 않는 조심스러운 실천',
    judgment: '호랑이 꼬리를 밟아도 물지 않으니 지극히 예의 바르게 행동하면 형통하리라.',
    imageAdvice: '하늘 위에 못이 있으니, 군자는 상하의 예를 분별하여 백성의 뜻을 세웁니다.',
    score: 85,
    grade: '길(吉)',
    actionGuidance: '위험한 상대나 까다로운 협상이라도 정중한 예의와 원칙을 지키면 승리합니다.',
    fortuneAspects: {
      wealth: '고수익 고위험 투자는 위험하니 안전자산 위주로 신중히 운용하세요.',
      career: '상사나 까다로운 클라이언트 앞에서도 침착한 태도로 위기를 기회로 바꿉니다.',
      love: '상대의 선을 넘지 않는 배려와 존중이 관계를 굳건히 지켜줍니다.',
      health: '발목이나 관절 부상을 조심하고 보행 시 주의를 기울이세요.',
    },
  },
  {
    num: 11,
    nameKr: '지천태(地天泰)',
    nameHanja: '泰',
    upperKey: '곤',
    lowerKey: '건',
    symbolMeaning: '땅의 기운은 내려오고 하늘의 기운은 올라가 천지가 교감하는 태평성대',
    judgment: '작은 것은 가고 큰 것이 오니 지극히 길하고 형통하여 만사가 순풍을 탑니다.',
    imageAdvice: '천지가 교감하여 만물이 번창하니, 군자는 천지의 도를 이룩합니다.',
    score: 99,
    grade: '대길(大吉)',
    actionGuidance: '주역 64괘 중 으뜸가는 태평대길의 괘입니다. 원하는 모든 소망을 과감히 펼치세요.',
    fortuneAspects: {
      wealth: '막혔던 자금줄이 시원하게 뚫리고 풍요로운 수확과 횡재가 따릅니다.',
      career: '승진, 사업 번창, 파트너십 체결, 모든 시험과 평가에서 독보적 1위입니다.',
      love: '혼담이 오가고 부부금슬이 백년해로로 이어지는 완벽한 인연운입니다.',
      health: '기혈이 화평하고 지병이 깨끗이 쾌차하여 활력이 샘솟습니다.',
    },
  },
  {
    num: 12,
    nameKr: '천지비(天地否)',
    nameHanja: '否',
    upperKey: '건',
    lowerKey: '곤',
    symbolMeaning: '하늘은 위로만 가고 땅은 아래로만 내려가 소통이 끊긴 답답한 정체기',
    judgment: '군자의 도는 가고 소인의 도가 득세하니, 덕을 감추고 어려움을 피하라.',
    imageAdvice: '천지가 소통하지 않으니, 군자는 검소한 덕으로 흉액을 피합니다.',
    score: 66,
    grade: '주의(注意)',
    actionGuidance: '지금은 무리하게 돌파하려 하지 말고 조용히 침묵하며 실력을 감출 때입니다.',
    fortuneAspects: {
      wealth: '지출을 엄격히 통제하고 새로운 투자나 보증은 일절 피하세요.',
      career: '조직 내 불통이나 인사 정체로 답답할 수 있으니 독자 행동을 삼가세요.',
      love: '대화의 단절이 생길 수 있으니 억지 설득보다 시간을 두고 기다리세요.',
      health: '가슴 답답함이나 소화불량을 주의하고 명상과 산책으로 심신을 달래세요.',
    },
  },
  {
    num: 13,
    nameKr: '천화동인(天火同人)',
    nameHanja: '同人',
    upperKey: '건',
    lowerKey: '리',
    symbolMeaning: '하늘 아래 밝은 불빛이 널리 비추어 뜻을 같이하는 동지들이 사방에서 모임',
    judgment: '들판에서 사람들과 뜻을 합하니 형통하며, 큰 내를 건넘에 이로우니라.',
    imageAdvice: '하늘과 불이 함께 빛나니, 군자는 족속을 분별하고 만물을 조화롭게 합니다.',
    score: 95,
    grade: '대길(大吉)',
    actionGuidance: '사리사욕을 버리고 공공의 이익을 도모하면 천하의 귀인들이 돕습니다.',
    fortuneAspects: {
      wealth: '투자 유치, 크라우드 펀딩, 공동 프로젝트에서 대박 수익을 올립니다.',
      career: '뜻맞는 동료들과 원대한 팀을 결성하여 혁신적인 성과를 창출합니다.',
      love: '친구처럼 편안하면서도 열정적인 소울메이트를 만나게 됩니다.',
      health: '시력과 심장 건강이 튼튼해지며 일상에 생동감이 넘칩니다.',
    },
  },
  {
    num: 14,
    nameKr: '화천대유(火天大有)',
    nameHanja: '大有',
    upperKey: '리',
    lowerKey: '건',
    symbolMeaning: '드높은 하늘 한가운데 찬란한 태양이 떠올라 만물을 비추는 거대한 소유',
    judgment: '지극히 크게 소유하여 번창하니, 덕을 베풀고 순응하면 지극히 형통하리라.',
    imageAdvice: '불이 하늘 위에 있으니, 군자는 악을 막고 선을 북돋아 천명을 따릅니다.',
    score: 98,
    grade: '대길(大吉)',
    actionGuidance: '명예와 부귀를 한 손에 거머쥐는 최고의 시기입니다. 겸손하게 복을 나누세요.',
    fortuneAspects: {
      wealth: '금고가 넘쳐나고 사업체 규모가 비약적으로 도약하는 최고봉 재물운입니다.',
      career: '모든 사람들의 선망을 받는 리더로 등극하며 탁월한 업적을 세웁니다.',
      love: '화려하고 품격 있는 이상형의 사랑을 한몸에 받게 됩니다.',
      health: '신체가 건장하고 활력이 넘치나 과로에 의한 열기를 식혀주세요.',
    },
  },
  {
    num: 15,
    nameKr: '지산겸(地山謙)',
    nameHanja: '謙',
    upperKey: '곤',
    lowerKey: '간',
    symbolMeaning: '높은 산이 스스로를 낮추어 넓은 땅속으로 들어간 지극한 겸손의 미덕',
    judgment: '겸손함은 형통하니, 군자는 끝까지 겸손을 지켜 복을 온전히 누리리라.',
    imageAdvice: '땅속에 높은 산이 있으니, 군자는 많은 것을 덜어 적은 데 보태며 공평히 합니다.',
    score: 96,
    grade: '대길(大吉)',
    actionGuidance: '벼는 익을수록 고개를 숙입니다. 겸손할수록 하늘과 사람이 모두 돕습니다.',
    fortuneAspects: {
      wealth: '드러나지 않는 알짜배기 자산이 조용하고 단단하게 불어납니다.',
      career: '적을 만들지 않는 처세술로 주위의 존경을 한몸에 받으며 장기 집권합니다.',
      love: '진솔하고 배려 깊은 태도로 상대방의 마음을 완전히 사로잡습니다.',
      health: '마음의 평정을 찾아 불면증과 신경성 질환이 말끔히 사라집니다.',
    },
  },
  {
    num: 16,
    nameKr: '뇌지예(雷地豫)',
    nameHanja: '豫',
    upperKey: '진',
    lowerKey: '곤',
    symbolMeaning: '대지 위로 우레가 진동하여 봄의 생명력이 움트며 즐거움과 환희가 넘침',
    judgment: '군사를 일으키고 제후를 봉함에 이로우니, 기쁨으로 세상을 감화시키리라.',
    imageAdvice: '우레가 땅 위로 터져 나오니, 군자는 음악을 짓고 덕을 찬미합니다.',
    score: 91,
    grade: '길(吉)',
    actionGuidance: '오랫동안 준비해 온 일을 세상에 발표하고 축제의 기쁨을 만끽할 때입니다.',
    fortuneAspects: {
      wealth: '엔터테인먼트, 예술, 축제, 홍보 마케팅을 통한 수익이 급증합니다.',
      career: '사기를 드높이고 팀을 흥겹게 이끌어 기대 이상의 성과를 창출합니다.',
      love: '즐거운 데이트와 파티에서 매력적인 인연을 만나 연인으로 발전합니다.',
      health: '우울감이 사라지고 활력이 솟구치나 과음이나 유흥을 절제하세요.',
    },
  },
  {
    num: 17,
    nameKr: '택뢰수(澤雷隨)',
    nameHanja: '隨',
    upperKey: '태',
    lowerKey: '진',
    symbolMeaning: '못 속에 우레가 잠겨 때를 기다리며 세상의 순리와 대세에 순응함',
    judgment: '시류를 따르며 곧고 바르면 허물이 없으니, 크게 형통하리라.',
    imageAdvice: '못 속에 우레가 있으니, 군자는 날이 저물면 편안히 쉬며 때를 기다립니다.',
    score: 87,
    grade: '길(吉)',
    actionGuidance: '고집을 부리지 말고 대세와 트렌드에 유연하게 순응할 때 가장 큰 이익이 생깁니다.',
    fortuneAspects: {
      wealth: '시장의 유행과 트렌드에 부합하는 아이템에 투자하면 길합니다.',
      career: '선배나 멘토의 지침을 충실히 따를 때 실패 없이 순조롭게 성장합니다.',
      love: '상대방의 취향을 맞춰주고 경청해 주면 깊은 애정이 싹틉니다.',
      health: '무리한 운동을 삼가고 휴식과 수면의 리듬을 지키세요.',
    },
  },
  {
    num: 18,
    nameKr: '산풍고(山風蠱)',
    nameHanja: '蠱',
    upperKey: '간',
    lowerKey: '손',
    symbolMeaning: '그릇 속에 벌레가 생기듯 오랜 부패와 묵은 병폐를 과감히 개혁해야 할 때',
    judgment: '선천삼일 후천삼일이라, 부패를 혁신하고 새롭게 다스리면 크게 길하리라.',
    imageAdvice: '산 아래 바람이 갇혔으니, 군자는 백성을 진작시키고 덕을 기릅니다.',
    score: 75,
    grade: '주의(注意)',
    actionGuidance: '곪은 상처는 도려내야 새살이 돋습니다. 묵은 문제점을 오늘 바로 뜯어고치세요.',
    fortuneAspects: {
      wealth: '새는 돈과 불필요한 고정 지출을 정리하고 재정 구조를 개혁하세요.',
      career: '잘못된 업무 프로세스를 전면 재정비하면 새로운 도약의 발판이 됩니다.',
      love: '서로 간에 묵혀두었던 갈등과 불만을 솔직하게 털어놓고 정화하세요.',
      health: '만성 피로, 체내 독소 배출, 디톡스와 식습관 개선이 시급합니다.',
    },
  },
  {
    num: 19,
    nameKr: '지택림(地澤臨)',
    nameHanja: '臨',
    upperKey: '곤',
    lowerKey: '태',
    symbolMeaning: '대지가 연못을 품고 백성에게 다가가 어질게 보살피는 지도자의 임함',
    judgment: '크게 형통하고 곧으니 길하나, 팔월에 이르면 흉함이 있을 것이니 대비하라.',
    imageAdvice: '땅 위에 못이 있으니, 군자는 가르침을 게을리하지 않고 백성을 용납합니다.',
    score: 93,
    grade: '대길(大吉)',
    actionGuidance: '운세가 상승세를 탔으니 주저하지 말고 기회를 잡으세요. 다만 하락기 대비도 함께!',
    fortuneAspects: {
      wealth: '매출과 영업 수익이 눈에 띄게 증가하며 귀인의 자금 지원이 따릅니다.',
      career: '아랫사람을 따뜻하게 지도하여 조직의 충성을 한몸에 받습니다.',
      love: '다정다감한 매력으로 상대의 마음을 편안하게 사로잡습니다.',
      health: '전반적인 컨디션이 양호하며 활기찬 일상을 누립니다.',
    },
  },
  {
    num: 20,
    nameKr: '풍지관(風地觀)',
    nameHanja: '觀',
    upperKey: '손',
    lowerKey: '곤',
    symbolMeaning: '바람이 땅 위를 두루 돌아보며 만물의 상태를 깊이 관찰하는 성찰의 상',
    judgment: '손을 씻고 제사를 올리기 직전의 경건한 마음으로 바라보면 신뢰를 얻으리라.',
    imageAdvice: '바람이 땅 위를 부니, 선왕은 사방을 살펴 백성을 교화합니다.',
    score: 85,
    grade: '길(吉)',
    actionGuidance: '성급하게 행동하지 말고 전후좌우 상황을 면밀히 관찰하고 통찰력을 기르세요.',
    fortuneAspects: {
      wealth: '투자 시장의 큰 흐름을 관망하며 확실한 매수 타이밍을 노리세요.',
      career: '기획, 시장 조사, 컨설팅, 분석 업무에서 탁월한 혜안을 발휘합니다.',
      love: '상대방의 진심을 조용히 지켜보고 이해하려는 배려가 빛을 발합니다.',
      health: '눈의 피로를 덜어주고 자연 풍경을 바라보며 힐링하세요.',
    },
  },
  {
    num: 21,
    nameKr: '화뢰서합(火雷噬嗑)',
    nameHanja: '噬嗑',
    upperKey: '리',
    lowerKey: '진',
    symbolMeaning: '입안에 뼈가 걸려 씹어 부수듯, 방해 요소를 단호하게 처벌하고 법을 세움',
    judgment: '옥사를 다스리고 형벌을 밝힘에 이로우니, 단호하게 결단하라.',
    imageAdvice: '우레와 번개가 함께 치니, 선왕은 형벌을 밝히고 법을 정합니다.',
    score: 83,
    grade: '길(吉)',
    actionGuidance: '우유부단함을 버리고 문제 요소를 과감하게 단속하고 처벌하여 기강을 세우세요.',
    fortuneAspects: {
      wealth: '미수금 회수, 채권 정리를 단호하게 매듭짓기에 적기입니다.',
      career: '부조리한 관행을 척결하고 정당한 평가 시스템을 확립합니다.',
      love: '오해나 제3자의 훼방을 단호하게 차단하여 관계의 순수성을 지키세요.',
      health: '치아 건강, 구강 질환, 턱관절 통증을 점검하세요.',
    },
  },
  {
    num: 22,
    nameKr: '산화비(山火賁)',
    nameHanja: '賁',
    upperKey: '간',
    lowerKey: '리',
    symbolMeaning: '산 아래 아름다운 불빛이 비추어 자연의 절경을 곱게 꾸미는 문채의 상',
    judgment: '작은 일에 나아감에 형통하니, 외면의 화려함보다 내면의 진실을 가꾸라.',
    imageAdvice: '산 아래 불이 있으니, 군자는 서정을 밝히되 옥사는 감히 결단하지 않습니다.',
    score: 84,
    grade: '길(吉)',
    actionGuidance: '디자인, 브랜딩, 품격을 다듬기에 최적입니다. 겉치레보다 실속을 챙기세요.',
    fortuneAspects: {
      wealth: '예술품, 인테리어, 뷰티, 패션 관련 사업에서 유익한 소득이 생깁니다.',
      career: '프레젠테이션이나 제안서의 시각적 완성도를 높여 극찬을 받습니다.',
      love: '세련된 옷차림과 매너로 첫인상에서 호감을 강하게 심어줍니다.',
      health: '피부 관리와 혈색 개선에 좋은 계절 과일을 섭취하세요.',
    },
  },
  {
    num: 23,
    nameKr: '산지박(山地剝)',
    nameHanja: '剝',
    upperKey: '간',
    lowerKey: '곤',
    symbolMeaning: '산이 땅 위에서 깎여 내려앉듯 음의 기운이 양을 깎아내는 쇠퇴와 박탈',
    judgment: '나아가는 바를 두지 말라. 소인이 득세하니 조용히 자리를 지키라.',
    imageAdvice: '산이 땅에 부착되어 있으니, 윗사람은 아랫사람을 두텁게 하여 편안케 합니다.',
    score: 64,
    grade: '험(險)',
    actionGuidance: '지금은 확장을 멈추고 손실을 최소화하는 방어적 태세를 취해야 할 때입니다.',
    fortuneAspects: {
      wealth: '무리한 대출이나 투자는 큰 낭패를 봅니다. 현금을 최대한 비축하세요.',
      career: '구설수나 모함에 휘말리지 않도록 언행을 극도로 자중하고 침묵하세요.',
      love: '사소한 꼬투리로 이별수가 감도니 논쟁을 피하고 인내하세요.',
      health: '면역력 급감과 관절, 허리 질환을 조심하고 과로를 피하세요.',
    },
  },
  {
    num: 24,
    nameKr: '지뢰복(地雷復)',
    nameHanja: '復',
    upperKey: '곤',
    lowerKey: '진',
    symbolMeaning: '어둠의 동지를 지나 땅속에서 양의 기운이 다시 솟구쳐 오르는 희망의 부활',
    judgment: '왔다 다시 돌아오니 칠일 만에 회복하리라. 나아감에 이로우니라.',
    imageAdvice: '땅속에 우레가 있으니, 선왕은 동짓날에 관문을 닫고 행인을 멈추게 합니다.',
    score: 93,
    grade: '대길(大吉)',
    actionGuidance: '고난의 터널이 끝났습니다. 서광이 비추니 희망찬 새 출발을 준비하세요.',
    fortuneAspects: {
      wealth: '바닥을 친 재정 상태가 회복세로 돌아서며 뜻밖의 수입이 생깁니다.',
      career: '슬럼프를 탈출하고 다시 자신감을 되찾아 새로운 기회를 포착합니다.',
      love: '헤어졌던 옛 인연과의 재회운이 있으며 서운했던 감정이 풀립니다.',
      health: '체력이 기적적으로 회복되고 오랜 환자가 자리를 털고 일어납니다.',
    },
  },
  {
    num: 25,
    nameKr: '천뢰무망(天雷无妄)',
    nameHanja: '无妄',
    upperKey: '건',
    lowerKey: '진',
    symbolMeaning: '하늘 아래 우레가 정직하게 울려 퍼지듯 거짓과 망상을 버리고 순수함을 지킴',
    judgment: '거짓이 없으면 크게 형통하니, 바르지 않으면 재앙이 있으리라.',
    imageAdvice: '하늘 아래 우레가 움직이니, 만물이 참된 본성대로 순응합니다.',
    score: 86,
    grade: '길(吉)',
    actionGuidance: '꼼수나 잔머리를 쓰지 말고 정직하게 정공법으로 나아가면 하늘이 돕습니다.',
    fortuneAspects: {
      wealth: '일확천금의 투기를 버리고 정당한 노동의 대가를 취할 때 부가 안전합니다.',
      career: '투명하고 청렴한 일 처리로 신뢰를 얻어 뜻밖의 포상을 받습니다.',
      love: '가식 없는 순수한 마음을 고백할 때 상대의 마음이 감동합니다.',
      health: '자연식 위주의 식단과 순수한 물 섭취로 몸의 균형을 되찾으세요.',
    },
  },
  {
    num: 26,
    nameKr: '산천대축(山天大畜)',
    nameHanja: '大畜',
    upperKey: '간',
    lowerKey: '건',
    symbolMeaning: '높은 산속에 드넓은 하늘의 기운을 가득 품고 있는 거대한 능력과 자산의 축적',
    judgment: '바르게 함에 이로우니, 집에서 밥 먹지 않고 벼슬길에 나아가도 길하리라.',
    imageAdvice: '산속에 하늘이 있으니, 군자는 옛 성현의 지혜를 많이 알아 덕을 기릅니다.',
    score: 96,
    grade: '대길(大吉)',
    actionGuidance: '오랫동안 쌓아온 실력과 자금이 마침내 거대한 에너지를 발휘할 황금기입니다.',
    fortuneAspects: {
      wealth: '목돈이 크게 모이고 튼튼한 알짜 자산을 구축하는 대길한 시기입니다.',
      career: '국가고시 합격, 박사 학위 취득, 대기업 및 고위직 등용의 운세입니다.',
      love: '성품이 깊고 든든한 배우자감을 만나 안정된 미래를 약속합니다.',
      health: '기운이 웅장하고 충만하여 심신이 건강합니다.',
    },
  },
  {
    num: 27,
    nameKr: '산뢰이(山雷頤)',
    nameHanja: '頤',
    upperKey: '간',
    lowerKey: '진',
    symbolMeaning: '위아래 턱을 벌려 음식을 씹듯, 말을 조심하고 올바른 양식을 취하는 기를 이',
    judgment: '바르게 하면 길하니, 스스로 먹거리를 살피고 입을 스스로 채우라.',
    imageAdvice: '산 아래 우레가 있으니, 군자는 언어를 삼가고 음식 조절을 잘합니다.',
    score: 83,
    grade: '길(吉)',
    actionGuidance: '입으로 들어가는 음식과 입에서 나오는 말을 각별히 삼가면 화를 면합니다.',
    fortuneAspects: {
      wealth: '요식업, 건강식품, 의료 분야에서 알찬 소득이 발생합니다.',
      career: '말실수를 조심하고 정확한 데이터와 문서로 소통하세요.',
      love: '따뜻한 밥 한 끼를 함께 나누며 정을 돈독히 쌓아가세요.',
      health: '과식이나 폭식을 멈추고 소화기 건강을 각별히 챙기세요.',
    },
  },
  {
    num: 28,
    nameKr: '택풍대과(澤風大過)',
    nameHanja: '大過',
    upperKey: '태',
    lowerKey: '손',
    symbolMeaning: '못이 나무를 집어삼키고 대들보가 휘어질 정도로 감당하기 힘든 중압감',
    judgment: '대들보가 휘어지니, 갈 바를 두면 형통하리라.',
    imageAdvice: '못이 나무를 멸하니, 군자는 홀로 서도 두려워하지 않고 세상에 은둔합니다.',
    score: 71,
    grade: '주의(注意)',
    actionGuidance: '자신의 역량을 초과하는 짐을 지고 있습니다. 분산하거나 조력자에게 나누세요.',
    fortuneAspects: {
      wealth: '무리한 대출이나 과도한 부채 상환 계획을 시급히 리파이낸싱하세요.',
      career: '과도한 책임감으로 번아웃이 올 수 있으니 업무를 과감히 위임하세요.',
      love: '상대를 너무 완벽하게 통제하려 하지 말고 숨 쉴 틈을 주십시오.',
      health: '허리 디스크, 척추 통증, 만성 피로를 경계하세요.',
    },
  },
  {
    num: 29,
    nameKr: '감위수(坎爲水)',
    nameHanja: '坎',
    upperKey: '감',
    lowerKey: '감',
    symbolMeaning: '험한 물길 위에 또 험한 소용돌이가 닥치는 중첩된 4대 난괘의 시련',
    judgment: '오직 진실한 마음이 있으면 형통하리니, 마음으로 행하면 숭상받으리라.',
    imageAdvice: '물이 겹쳐 흐르니, 군자는 덕행을 상습하고 교화를 거듭합니다.',
    score: 62,
    grade: '험(險)',
    actionGuidance: '물처럼 유연하게 낮은 곳으로 흐르며 마음의 중심을 지키면 결국 탈출합니다.',
    fortuneAspects: {
      wealth: '자금이 깊은 구덩이에 빠질 수 있으니 신규 투자는 절대 금물입니다.',
      career: '험난한 위기 상황이지만 중심을 잃지 않으면 오히려 큰 신망을 얻습니다.',
      love: '오해와 불신이 깊어질 수 있으니 묵묵한 진심으로 기다리세요.',
      health: '신장, 비뇨기 계통 질환 및 우울증, 익수 사고에 각별히 유의하세요.',
    },
  },
  {
    num: 30,
    nameKr: '리위화(離爲火)',
    nameHanja: '離',
    upperKey: '리',
    lowerKey: '리',
    symbolMeaning: '타오르는 불꽃이 서로 맞붙어 세상을 대낮처럼 밝히는 찬란한 광명',
    judgment: '암소를 기르면 길하리니, 바른 곳에 붙어야 영원히 타오를 수 있느니라.',
    imageAdvice: '밝음이 겹쳐 비추니, 대인은 밝은 덕을 계승하여 사방을 비춥니다.',
    score: 92,
    grade: '길(吉)',
    actionGuidance: '열정과 지성을 발휘하되 불이 연료에 의지하듯 든든한 기반을 지켜야 합니다.',
    fortuneAspects: {
      wealth: '예술, 미디어, 조명, IT 등 화려한 분야에서 고수익을 거둡니다.',
      career: '뛰어난 두뇌와 통찰력으로 시험 합격과 대중적 인기를 얻습니다.',
      love: '불꽃처럼 뜨거운 사랑을 나누나 너무 성급하면 쉽게 식을 수 있습니다.',
      health: '안과 질환, 혈압, 심장 두근거림을 주의하고 차분함을 유지하세요.',
    },
  },
  {
    num: 31,
    nameKr: '택산함(澤山咸)',
    nameHanja: '咸',
    upperKey: '태',
    lowerKey: '간',
    symbolMeaning: '산 위에 연못이 있어 청춘남녀가 첫눈에 반하듯 영혼이 깊이 감응하는 교감',
    judgment: '형통하니 바르게 함에 이로우며, 여자를 취하면 길하리라.',
    imageAdvice: '산 위에 못이 있으니, 군자는 허심탄회하게 사람들을 받아들입니다.',
    score: 97,
    grade: '대길(大吉)',
    actionGuidance: '마음의 빗장을 열고 진심으로 소통하세요. 놀라운 감동과 화답이 돌아옵니다.',
    fortuneAspects: {
      wealth: '고객과의 공감대 형성을 통한 영업 및 계약 성사율이 극에 달합니다.',
      career: '면접, 오디션, 발표에서 심사위원의 마음을 완벽히 사로잡습니다.',
      love: '평생을 함께할 운명적인 상대를 만나 첫눈에 사랑에 빠질 대길몽입니다.',
      health: '심신이 평온하고 기분 좋은 설렘으로 엔도르핀이 샘솟습니다.',
    },
  },
  {
    num: 32,
    nameKr: '뇌풍항(雷風恒)',
    nameHanja: '恒',
    upperKey: '진',
    lowerKey: '손',
    symbolMeaning: '우레와 바람이 서로 어우러져 변함없이 영원히 지속되는 한결같은 지속성',
    judgment: '형통하여 허물이 없으니 바르게 함에 이로우며, 갈 바를 둠에 이로우니라.',
    imageAdvice: '우레와 바람이 서로 따르니, 군자는 서서 방향을 바꾸지 않습니다.',
    score: 93,
    grade: '대길(大吉)',
    actionGuidance: '초심을 잃지 않고 꾸준히 밀고 나가면 마침내 커다란 결실을 맺습니다.',
    fortuneAspects: {
      wealth: '단기 투기보다 꾸준한 적금과 배당 투자로 안정적인 부를 축적합니다.',
      career: '한 분야에 묵묵히 헌신한 노력에 대한 마스터의 명성을 얻습니다.',
      love: '부부간의 백년해로, 오랜 연인과의 굳건한 신뢰가 빛납니다.',
      health: '생활 습관을 일정하게 유지하고 규칙적인 운동을 지속하세요.',
    },
  },
  {
    num: 33,
    nameKr: '천산둔(天山遯)',
    nameHanja: '遯',
    upperKey: '건',
    lowerKey: '간',
    symbolMeaning: '하늘 아래 산이 물러서듯 소인의 기운을 피해 은둔하고 때를 기다림',
    judgment: '물러남이 형통하니, 작은 일에 바르게 함이 이로우니라.',
    imageAdvice: '하늘 아래 산이 있으니, 군자는 소인을 멀리하되 엄숙하게 대합니다.',
    score: 72,
    grade: '주의(注意)',
    actionGuidance: '때가 아닐 때는 미련 없이 한 걸음 물러서는 것이 진정한 지혜이자 승리입니다.',
    fortuneAspects: {
      wealth: '무리한 확장을 멈추고 자금을 안전하게 회수하여 보존할 때입니다.',
      career: '사내 정쟁이나 파벌 싸움에서 한 발짝 떨어져 중립을 지키세요.',
      love: '잠시 각자의 시간을 갖고 거리를 두는 것이 관계 회복에 좋습니다.',
      health: '복잡한 도시를 떠나 자연 속에서 조용한 휴양을 취하세요.',
    },
  },
  {
    num: 34,
    nameKr: '뇌천대장(雷天大壯)',
    nameHanja: '大壯',
    upperKey: '진',
    lowerKey: '건',
    symbolMeaning: '하늘 위에서 우레가 맹렬히 진동하여 양의 기운이 지극히 왕성한 대장부',
    judgment: '바르게 함에 이로우니, 힘을 함부로 쓰지 말고 도리에 맞게 행동하라.',
    imageAdvice: '우레가 하늘 위에 있으니, 군자는 예가 아니면 밟지 않습니다.',
    score: 90,
    grade: '길(吉)',
    actionGuidance: '기운이 뻗쳐오르는 왕성한 시기이나, 숫양이 울타리를 들이받는 무모함은 경계하세요.',
    fortuneAspects: {
      wealth: '과감한 추진력으로 수익을 거두나 무리한 베팅은 자제해야 합니다.',
      career: '강력한 돌파력으로 경쟁사를 압도하며 시장을 선점합니다.',
      love: '자신의 매력을 적극적으로 어필하되 상대의 의견을 존중하세요.',
      health: '근육통, 타박상 등 격렬한 운동 중 부상에 유의하세요.',
    },
  },
  {
    num: 35,
    nameKr: '화지진(火地晉)',
    nameHanja: '晉',
    upperKey: '리',
    lowerKey: '곤',
    symbolMeaning: '대지 위로 붉은 태양이 솟아올라 빛이 사방을 비추는 승승장구와 고속 승진',
    judgment: '제후에게 말을 하사하고 하루에 세 번 접견하듯 영예가 넘치리라.',
    imageAdvice: '밝은 태양이 땅 위로 솟으니, 군자는 스스로 덕을 밝힙니다.',
    score: 96,
    grade: '대길(大吉)',
    actionGuidance: '햇살을 받은 초목처럼 모든 일이 급속도로 전진합니다. 기회를 놓치지 마세요.',
    fortuneAspects: {
      wealth: '재물운이 활짝 열리고 공공 입찰이나 보너스 수령의 기쁨이 있습니다.',
      career: '윗사람의 파격적인 천거를 받아 고속 승진과 영전의 영예를 안습니다.',
      love: '모든 사람의 축복을 받는 화사하고 당당한 연애를 펼칩니다.',
      health: '안색이 밝아지고 활력이 솟구치며 심신이 상쾌합니다.',
    },
  },
  {
    num: 36,
    nameKr: '지화명이(地火明夷)',
    nameHanja: '明夷',
    upperKey: '곤',
    lowerKey: '리',
    symbolMeaning: '찬란한 태양이 땅속으로 숨어들듯 재능을 감추고 어둠의 시련을 견딤',
    judgment: '어려움 속에서 바르게 함이 이로우니, 자신의 밝음을 감추어 화를 면하라.',
    imageAdvice: '밝음이 땅속으로 들어가니, 군자는 무리를 대하되 지혜를 감춥니다.',
    score: 63,
    grade: '험(險)',
    actionGuidance: '시기질투를 받기 쉬운 때입니다. 잘난 체하지 말고 바보인 척 덕을 숨기세요.',
    fortuneAspects: {
      wealth: '재산을 자랑하지 말고 은밀히 관리하며 사기를 극도로 경계하세요.',
      career: '상사의 눈밖에 나지 않도록 고개를 숙이고 조용히 내실을 다지세요.',
      love: '오해와 상처가 생길 수 있으니 맞서 싸우지 말고 침묵으로 넘기세요.',
      health: '시력 감퇴, 심장 질환, 화병과 우울감을 세심히 보살피세요.',
    },
  },
  {
    num: 37,
    nameKr: '풍화가인(風火家人)',
    nameHanja: '家人',
    upperKey: '손',
    lowerKey: '리',
    symbolMeaning: '바람이 불꽃을 일으켜 따뜻한 온기가 온 집안을 감싸는 화목한 가정',
    judgment: '여인이 바르게 함에 이로우니, 집안이 바로 서면 천하가 안정되리라.',
    imageAdvice: '바람이 불에서 나오니, 군자는 말에 실질이 있고 행동에 법도가 있습니다.',
    score: 94,
    grade: '대길(大吉)',
    actionGuidance: '가화만사성입니다. 가족과 팀원들의 화목과 신뢰를 다지면 바깥일도 술술 풀립니다.',
    fortuneAspects: {
      wealth: '가족 공동의 재산이 늘어나고 부동산 매입이나 인테리어에 길합니다.',
      career: '조직 구성원 간의 끈끈한 단합으로 난관을 순조롭게 돌파합니다.',
      love: '결혼이 성사되고 가족들의 열렬한 축복 속에 안락한 보금자리를 꾸밉니다.',
      health: '온 가족이 무탈하고 건강하며 평온한 휴식을 누립니다.',
    },
  },
  {
    num: 38,
    nameKr: '화택규(火澤睽)',
    nameHanja: '睽',
    upperKey: '리',
    lowerKey: '태',
    symbolMeaning: '불은 위로 타오르고 못은 아래로 고여 서로 곁눈질하며 반목하는 어긋남',
    judgment: '작은 일에는 길하나, 뜻이 서로 달라 큰일을 도모하기는 어려우니라.',
    imageAdvice: '불과 못이 서로 어긋나니, 군자는 동화되되 같아지지 않습니다.',
    score: 68,
    grade: '주의(注意)',
    actionGuidance: '상대방과의 차이를 인정하고 무리한 합의를 강요하지 마세요. 다름을 존중할 때!',
    fortuneAspects: {
      wealth: '동업자 간의 금전적 이견이 생기기 쉬우니 정산서를 명확히 하세요.',
      career: '팀원 간의 엇박자를 조율하고 각자의 강점을 살리는 역할 분담을 하세요.',
      love: '성격 차이로 다툴 수 있으니 서로의 독립된 영역을 인정해 주세요.',
      health: '안과 질환, 치통, 신경성 위장염에 주의하세요.',
    },
  },
  {
    num: 39,
    nameKr: '수산건(水山蹇)',
    nameHanja: '蹇',
    upperKey: '감',
    lowerKey: '간',
    symbolMeaning: '앞에는 험한 물결이 가로막고 뒤에는 높은 산이 솟아 발걸음이 무거운 4대 난괘',
    judgment: '서남쪽에 이롭고 동북쪽에는 불리하니, 대인을 봄이 이로우니라.',
    imageAdvice: '산 위에 물이 있으니, 군자는 몸을 돌이켜 덕을 닦습니다.',
    score: 62,
    grade: '험(險)',
    actionGuidance: '무리하게 직진하면 함정에 빠집니다. 경험 많은 원로의 조언을 구하고 우회하세요.',
    fortuneAspects: {
      wealth: '자금 흐름이 꽉 막힐 수 있으니 지출을 전면 동결하고 수성에 힘쓰세요.',
      career: '진퇴양난의 국면입니다. 무리한 강행을 멈추고 제3자의 중재를 받으세요.',
      love: '집안의 반대나 현실적인 장벽으로 교제가 정체될 수 있습니다.',
      health: '다리 부상, 관절염, 보행 시 미끄러짐 사고를 극도로 조심하세요.',
    },
  },
  {
    num: 40,
    nameKr: '뇌수해(雷水解)',
    nameHanja: '解',
    upperKey: '진',
    lowerKey: '감',
    symbolMeaning: '봄비가 내리고 우레가 울려 얼어붙은 얼음이 녹아내리듯 모든 곤경이 풀림',
    judgment: '서남쪽이 이로우니 갈 곳이 없거든 일찍 돌아오고, 갈 곳이 있거든 속히 행하라.',
    imageAdvice: '우레와 비가 함께 작용하니, 군자는 허물을 용서하고 죄를 사면합니다.',
    score: 95,
    grade: '대길(大吉)',
    actionGuidance: '모든 묵은 빚과 오해, 소송, 난제가 눈 녹듯 풀리는 대역전 해방의 시기입니다.',
    fortuneAspects: {
      wealth: '묶였던 자금이 풀리고 부채가 해결되며 신규 자금이 원활히 유입됩니다.',
      career: '정체되었던 프로젝트가 급물살을 타고 승인 및 계약이 체결됩니다.',
      love: '오랜 갈등이 화해로 전환되고 새로운 설렘의 문이 활짝 열립니다.',
      health: '오랜 투병 생활을 끝내고 건강을 완전히 회복하는 반가운 서광입니다.',
    },
  },
  {
    num: 41,
    nameKr: '산택손(山澤損)',
    nameHanja: '損',
    upperKey: '간',
    lowerKey: '태',
    symbolMeaning: '연못을 파서 산을 높이듯 아래를 덜어 위를 보태는 절제와 봉사의 상',
    judgment: '정성이 있으면 크게 길하니, 두 그릇의 소박한 제물로도 신명께 닿으리라.',
    imageAdvice: '산 아래 못이 있으니, 군자는 분노를 가라앉히고 욕망을 막습니다.',
    score: 82,
    grade: '평(平)',
    actionGuidance: '눈앞의 작은 손실을 아까워하지 마세요. 베풀고 비운 자리에 더 큰 복이 채워집니다.',
    fortuneAspects: {
      wealth: '초기 비용이나 투자 지출이 있으나 장기적으로 몇 배의 수익으로 돌아옵니다.',
      career: '조직을 위해 헌신한 노고가 윗사람에게 각인되어 두터운 신임을 얻습니다.',
      love: '자신의 욕심을 내려놓고 연인을 배려할 때 진정한 감동이 찾아옵니다.',
      health: '소식(小食)과 절제로 몸의 독소를 비우면 건강이 배가됩니다.',
    },
  },
  {
    num: 42,
    nameKr: '풍뢰익(風雷益)',
    nameHanja: '益',
    upperKey: '손',
    lowerKey: '진',
    symbolMeaning: '바람과 우레가 서로를 북돋워 만물에 이로움을 더하는 비약적인 성장과 증식',
    judgment: '갈 바를 둠에 이로우며 큰 내를 건넘에 이로우니라.',
    imageAdvice: '바람과 우레가 더하니, 군자는 착한 것을 보면 따르고 허물이 있으면 고칩니다.',
    score: 97,
    grade: '대길(大吉)',
    actionGuidance: '투자, 사업 확장, 새로운 시작에 최고의 기운입니다. 적극적으로 공세를 펼치세요.',
    fortuneAspects: {
      wealth: '재물이 나날이 불어나고 뜻밖의 후원금과 계약이 쏟아져 들어옵니다.',
      career: '사회적 영향력이 비약적으로 커지고 추진하는 일마다 대성공을 거둡니다.',
      love: '서로에게 복을 불러주는 복덩이 인연을 만나 나날이 행복합니다.',
      health: '생명력이 넘치고 원기가 회복되어 피로를 모르는 하루를 보냅니다.',
    },
  },
  {
    num: 43,
    nameKr: '택천쾌(澤天夬)',
    nameHanja: '夬',
    upperKey: '태',
    lowerKey: '건',
    symbolMeaning: '하늘 위에 못물이 차올라 둑을 트듯 결단을 내려 마지막 남은 소인을 결단함',
    judgment: '조정에 알리고 부르짖되 무력을 쓰지 말고 온건하게 결단하라.',
    imageAdvice: '못이 하늘 위로 오르니, 군자는 녹봉을 베풀어 아래까지 닿게 합니다.',
    score: 84,
    grade: '길(吉)',
    actionGuidance: '우유부단함을 끝내고 과감하게 결단을 내리세요. 단, 감정적인 폭력은 삼가야 합니다.',
    fortuneAspects: {
      wealth: '부실 자산을 과감하게 손절매하고 알짜배기로 갈아탈 때입니다.',
      career: '지연되던 계약이나 인사를 단호하게 매듭지어 추진력을 확보합니다.',
      love: '애매모호한 삼각관계나 미련을 깔끔하게 정리하고 새 길을 가세요.',
      health: '종기나 염증 부위를 치료하고 신체의 결함을 수술하기에 적기입니다.',
    },
  },
  {
    num: 44,
    nameKr: '천풍구(天風姤)',
    nameHanja: '姤',
    upperKey: '건',
    lowerKey: '손',
    symbolMeaning: '하늘 아래 바람이 불어 뜻밖의 기이한 인연을 우연히 만나는 조우의 상',
    judgment: '여자가 굳세니 장가들지 말라. 우연한 만남에 속마음을 경계하라.',
    imageAdvice: '하늘 아래 바람이 부니, 군자는 사방에 명령을 반포합니다.',
    score: 75,
    grade: '주의(注意)',
    actionGuidance: '뜻밖의 매혹적인 제안이나 인연이 다가오나, 겉모습에 홀리지 말고 내면을 검증하세요.',
    fortuneAspects: {
      wealth: '달콤한 수익을 미끼로 다가오는 다단계나 불투명한 유혹을 단호히 거절하세요.',
      career: '갑작스러운 파트너십 제안은 조항을 세밀히 검토한 후 결정하세요.',
      love: '강렬하게 끌리는 이성을 만나나 감정의 롤러코스터에 휘말릴 수 있습니다.',
      health: '전염성 질환이나 계절성 알레르기 질환에 주의하세요.',
    },
  },
  {
    num: 45,
    nameKr: '택지췌(澤地萃)',
    nameHanja: '萃',
    upperKey: '태',
    lowerKey: '곤',
    symbolMeaning: '대지 위에 연못이 모여들듯 인재와 재물이 구름처럼 한곳으로 결집함',
    judgment: '왕이 종묘에 이르듯 형통하니, 큰 인물을 만나고 큰 내를 건넘에 이롭도다.',
    imageAdvice: '못이 땅 위에 모이니, 군자는 무기를 정비하여 뜻밖의 일에 대비합니다.',
    score: 95,
    grade: '대길(大吉)',
    actionGuidance: '사람과 자본이 모여드는 황금기입니다. 규율을 정비하고 결속력을 다지세요.',
    fortuneAspects: {
      wealth: '투자금 유치, 자본 집결, 매장 고객 급증으로 매출이 폭발합니다.',
      career: '훌륭한 인재들을 영입하여 강력한 드림팀을 구축합니다.',
      love: '많은 이성들의 찬사와 고백을 받으며 행복한 선택의 고민을 합니다.',
      health: '기혈이 충만하나 과식으로 인한 체중 증가와 비만을 조절하세요.',
    },
  },
  {
    num: 46,
    nameKr: '지풍승(地風升)',
    nameHanja: '升',
    upperKey: '곤',
    lowerKey: '손',
    symbolMeaning: '땅속에서 자라난 작은 나무가 거목으로 자라나듯 끊임없이 상승하는 발전',
    judgment: '크게 형통하니 대인을 만나 근심하지 말고 남쪽으로 나아가라.',
    imageAdvice: '땅속에서 나무가 자라나니, 군자는 덕에 순응하여 작은 것으로 큰 것을 쌓습니다.',
    score: 96,
    grade: '대길(大吉)',
    actionGuidance: '성장의 사다리를 타고 올라가는 시기입니다. 윗사람의 후원을 받아 승진을 거머쥐세요.',
    fortuneAspects: {
      wealth: '점진적이고 확실하게 자산 가치가 상승하여 큰 부를 이룹니다.',
      career: '차근차근 승진하여 고위직에 오르며 실력을 확실히 인정받습니다.',
      love: '처음에는 서먹했으나 시간이 흐를수록 깊어지는 진국 같은 인연입니다.',
      health: '신체의 유연성을 기르고 키나 체력 증진에 매우 유리합니다.',
    },
  },
  {
    num: 47,
    nameKr: '택수곤(澤水困)',
    nameHanja: '困',
    upperKey: '태',
    lowerKey: '감',
    symbolMeaning: '연못 밑으로 물이 다 빠져나가 말라비틀어진 극한의 고난과 시험(4대 난괘)',
    judgment: '말을 해도 믿지 않으리니 오직 침묵하며 대인의 도리로 버텨내라.',
    imageAdvice: '못에 물이 없으니, 군자는 목숨을 바쳐 뜻을 이룹니다.',
    score: 60,
    grade: '험(險)',
    actionGuidance: '변명하거나 다투지 마세요. 묵묵히 시련을 견뎌내면 금이 불 속에서 단련되듯 거듭납니다.',
    fortuneAspects: {
      wealth: '유동성 위기가 닥칠 수 있으니 긴축재정으로 비상사태에 대비하세요.',
      career: '오해를 받거나 능력을 인정받기 어려우니 묵묵히 자리를 지키세요.',
      love: '서로에게 상처를 주기 쉬우니 잠시 감정을 가라앉히고 자중하세요.',
      health: '탈수 증세, 만성 피로, 목과 인후통 질환에 각별히 유의하세요.',
    },
  },
  {
    num: 48,
    nameKr: '수풍정(水風井)',
    nameHanja: '井',
    upperKey: '감',
    lowerKey: '손',
    symbolMeaning: '마을은 바뀌어도 마르지 않고 만인을 먹여 살리는 깊고 시원한 우물',
    judgment: '우물을 두레박으로 길어 올리되 두레박 줄이 끊어지지 않게 조심하라.',
    imageAdvice: '나무 위에 물이 있으니, 군자는 백성을 위로하고 서로 권면합니다.',
    score: 89,
    grade: '길(吉)',
    actionGuidance: '마르지 않는 실력과 인성을 갖추세요. 널리 베풀수록 당신의 가치는 높아집니다.',
    fortuneAspects: {
      wealth: '정기적인 배당금, 로열티, 연금 등 고정적인 파이프라인 수입이 튼튼해집니다.',
      career: '대체 불가능한 전문가로서 조직의 기둥 역할을 확고히 합니다.',
      love: '마르지 않는 샘물처럼 한결같이 퍼주는 헌신적인 사랑이 결실을 맺습니다.',
      health: '신선한 천연 암반수나 물을 충분히 섭취하여 신진대사를 촉진하세요.',
    },
  },
  {
    num: 49,
    nameKr: '택화혁(澤火革)',
    nameHanja: '革',
    upperKey: '태',
    lowerKey: '리',
    symbolMeaning: '물과 불이 싸워 묵은 껍질을 벗겨내고 완전히 새롭게 거듭나는 위대한 변혁',
    judgment: '그날이 이르러야 믿으리니, 크게 형통하고 바르게 함에 뉘우침이 없으리라.',
    imageAdvice: '못 속에 불이 있으니, 군자는 책력을 고쳐 때를 밝힙니다.',
    score: 93,
    grade: '대길(大吉)',
    actionGuidance: '구태의연한 낡은 방식을 과감히 폐기하고 혁신적인 시스템으로 갈아치울 때입니다.',
    fortuneAspects: {
      wealth: '새로운 성장 산업이나 패러다임 전환 분야로 포트폴리오를 전환하세요.',
      career: '구조조정, 업종 전환, 대대적인 혁신 프로젝트를 주도하여 승리합니다.',
      love: '낡은 연애 패턴을 탈피하고 새로운 마음가짐으로 관계를 리셋하세요.',
      health: '체질 개선, 다이어트, 식단 개혁에 최상의 성공률을 보입니다.',
    },
  },
  {
    num: 50,
    nameKr: '화풍정(火風鼎)',
    nameHanja: '鼎',
    upperKey: '리',
    lowerKey: '손',
    symbolMeaning: '세 발 달린 솥에 음식을 끓여 신명과 백성을 대접하는 정권 창출과 안착',
    judgment: '원형이정(元吉) - 지극히 길하고 형통하여 위대한 업적을 계승하리라.',
    imageAdvice: '나무 위에 불이 있으니, 군자는 자리를 바르게 하여 사명을 굳게 합니다.',
    score: 98,
    grade: '대길(大吉)',
    actionGuidance: '주역에서 지천태와 함께 최고의 복을 상징합니다. 권좌에 올라 국태민안을 이룹니다.',
    fortuneAspects: {
      wealth: '가문 대대로 이어질 탄탄한 가업과 재산 기반을 확립합니다.',
      career: '최고 권력자의 신임을 얻어 중책을 맡고 역사의 주역으로 부상합니다.',
      love: '이상적인 배우자를 만나 화목하고 존경받는 명문 가정을 꾸립니다.',
      health: '영양 상태가 완벽하고 건강과 장수를 누릴 길조입니다.',
    },
  },
  {
    num: 51,
    nameKr: '진위뇌(震爲雷)',
    nameHanja: '震',
    upperKey: '진',
    lowerKey: '진',
    symbolMeaning: '우레가 백 리를 울리며 세상을 깜짝 놀라게 하듯 위엄과 경각심의 폭발',
    judgment: '우레가 올 때 두려워하여 삼가면 웃음꽃이 피고, 제사를 잃지 않으리라.',
    imageAdvice: '우레가 거듭 울리니, 군자는 두려워하며 반성하고 수양합니다.',
    score: 84,
    grade: '길(吉)',
    actionGuidance: '갑작스러운 돌발 상황에 당황하지 말고 침착하게 대응하면 전화위복이 됩니다.',
    fortuneAspects: {
      wealth: '갑작스러운 시장 변동성이 크니 추격매수를 자제하고 냉정을 지키세요.',
      career: '위기관리 능력을 발휘하여 동요하는 조직을 진정시키고 리더십을 입증합니다.',
      love: '깜짝 놀랄 고백이나 서프라이즈 이벤트를 통해 호감을 얻습니다.',
      health: '신경 과민과 심장 두근거림을 주의하고 카페인 섭취를 줄이세요.',
    },
  },
  {
    num: 52,
    nameKr: '간위산(艮爲山)',
    nameHanja: '艮',
    upperKey: '간',
    lowerKey: '간',
    symbolMeaning: '산 위에 또 산이 우뚝 서서 멈추어야 할 때 멈추는 부동심(不動心)의 굳건함',
    judgment: '등을 멈추어 몸을 얻지 못하며 뜰에 가도 사람을 보지 못하니 허물이 없느니라.',
    imageAdvice: '산이 겹쳐 있으니, 군자는 생각이 그 자리를 벗어나지 않습니다.',
    score: 83,
    grade: '길(吉)',
    actionGuidance: '움직일 때가 아니면 바위처럼 멈추어 서서 고요히 마음을 비우는 것이 최선입니다.',
    fortuneAspects: {
      wealth: '자산을 움직이지 말고 현 상태로 단단히 묶어두는 것이 최선의 재테크입니다.',
      career: '무리한 이직이나 확장을 멈추고 현재 맡은 임무의 내실을 다지세요.',
      love: '상대에게 지나치게 간섭하지 말고 침묵과 거리두기로 마음을 정돈하세요.',
      health: '허리, 척추, 목 디스크 통증을 점검하고 바른 자세를 유지하세요.',
    },
  },
  {
    num: 53,
    nameKr: '풍산점(風山漸)',
    nameHanja: '漸',
    upperKey: '손',
    lowerKey: '간',
    symbolMeaning: '기러기가 차례대로 날아오르듯 순서에 맞추어 점진적으로 나아가는 순조로움',
    judgment: '여자가 시집감에 길하니, 바르게 함에 이로우니라.',
    imageAdvice: '산 위에 나무가 자라나니, 군자는 현덕을 쌓아 풍속을 선하게 바꿉니다.',
    score: 95,
    grade: '대길(大吉)',
    actionGuidance: '급하게 서두르지 말고 계단을 밟듯 정석대로 나아가면 반드시 성공합니다.',
    fortuneAspects: {
      wealth: '복리 이자처럼 차곡차곡 쌓여 거대한 자산으로 불어납니다.',
      career: '정규직 전환, 단계적 승진, 논문 통과 등 순조로운 성공 가도를 달립니다.',
      love: '연애에서 결혼으로, 양가 상견례와 혼담이 물 흐르듯 순조롭게 진행됩니다.',
      health: '꾸준한 걷기 운동과 규칙적인 식습관으로 기초체력이 튼튼해집니다.',
    },
  },
  {
    num: 54,
    nameKr: '뇌택귀매(歸妹)',
    nameHanja: '歸妹',
    upperKey: '진',
    lowerKey: '태',
    symbolMeaning: '소녀가 감정에 이끌려 순서를 무시하고 시집가듯 충동과 절차 무시의 경계',
    judgment: '나아가면 흉하니 유익한 바가 없느니라.',
    imageAdvice: '못 위에 우레가 있으니, 군자는 영원함을 알고 결함을 살핍니다.',
    score: 66,
    grade: '주의(注意)',
    actionGuidance: '감정에 휩쓸려 충동적으로 결정하지 마세요. 절차와 순리를 철저히 지키십시오.',
    fortuneAspects: {
      wealth: '충동구매와 투기성 베팅을 자제하고 사기 피해를 조심하세요.',
      career: '편법이나 지름길을 택하다가 원칙 위반으로 징계를 받을 수 있습니다.',
      love: '순간의 불꽃에 이끌려 서두르다 후회할 수 있으니 시간을 두고 관찰하세요.',
      health: '부인과 질환이나 감정 기복으로 인한 소화불량을 주의하세요.',
    },
  },
  {
    num: 55,
    nameKr: '뇌화풍(雷火豐)',
    nameHanja: '豐',
    upperKey: '진',
    lowerKey: '리',
    symbolMeaning: '우레와 번개가 천하를 진동하며 대낮의 태양처럼 풍요로움이 극에 달함',
    judgment: '왕이 천하를 풍요롭게 하니, 근심하지 말고 정오의 태양처럼 밝게 비추라.',
    imageAdvice: '우레와 번개가 함께 이르니, 군자는 옥사를 결단하고 형벌을 집행합니다.',
    score: 94,
    grade: '대길(大吉)',
    actionGuidance: '풍요와 번영의 정점에 서 있습니다. 해가 서산으로 기울기 전에 결실을 수확하세요.',
    fortuneAspects: {
      wealth: '사업 매출과 금융 수익이 최고조에 달하여 풍성한 수확을 거둡니다.',
      career: '세상의 스포트라이트를 받으며 프로젝트를 대성공으로 이끕니다.',
      love: '화려하고 열정적인 사랑을 나누며 주변의 부러움을 삽니다.',
      health: '혈압과 심혈관 계통 건강을 잘 챙기고 무리한 흥분을 가라앉히세요.',
    },
  },
  {
    num: 56,
    nameKr: '화산려(火山旅)',
    nameHanja: '旅',
    upperKey: '리',
    lowerKey: '간',
    symbolMeaning: '산 위에 붙은 불이 이리저리 옮겨 붙듯 나그네가 길을 떠나는 유랑의 상',
    judgment: '작은 일에 형통하니, 나그네의 도리는 바르게 함에 있느니라.',
    imageAdvice: '산 위에 불이 있으니, 군자는 밝게 살피고 형벌을 신중히 합니다.',
    score: 74,
    grade: '평(平)',
    actionGuidance: '낯선 환경에 처해 있으니 교만을 버리고 겸손과 예의를 지켜야 안전합니다.',
    fortuneAspects: {
      wealth: '출장이나 여행 경비 지출이 많으니 지갑 단속을 철저히 하세요.',
      career: '출장, 파견, 해외 근무, 이직 등 이동수가 강하게 작용합니다.',
      love: '여행지나 낯선 장소에서 뜻밖의 인연을 만나나 단기성에 그칠 수 있습니다.',
      health: '풍토병, 시차 적응, 소화기 질환에 주의하고 위생을 챙기세요.',
    },
  },
  {
    num: 57,
    nameKr: '손위풍(巽爲風)',
    nameHanja: '巽',
    upperKey: '손',
    lowerKey: '손',
    symbolMeaning: '바람 위에 또 바람이 불어 틈새마다 스며들듯 유순하고 지혜롭게 순응함',
    judgment: '작은 일에 형통하니, 갈 바를 둠에 이롭고 대인을 봄에 이로우니라.',
    imageAdvice: '바람이 거듭 부니, 군자는 명령을 널리 펴고 일을 행합니다.',
    score: 88,
    grade: '길(吉)',
    actionGuidance: '강하게 부딪히지 말고 부드러운 바람처럼 유연하게 스며들 때 마음을 얻습니다.',
    fortuneAspects: {
      wealth: '소규모 무역, 유통, 커뮤니케이션을 통해 알뜰한 수익을 창출합니다.',
      career: '부드러운 협상력과 설득력으로 까다로운 계약을 성사시킵니다.',
      love: '상대의 마음을 살피는 섬세한 배려와 다정함이 사랑을 꽃피웁니다.',
      health: '호흡기, 기관지 질환을 주의하고 신선한 공기를 마시세요.',
    },
  },
  {
    num: 58,
    nameKr: '태위택(兌爲澤)',
    nameHanja: '兌',
    upperKey: '태',
    lowerKey: '태',
    symbolMeaning: '두 개의 연못이 서로 물을 대어주며 기쁨과 웃음이 끊이지 않는 화락의 상',
    judgment: '기쁨이 넘쳐 형통하니, 바르게 함에 이로우니라.',
    imageAdvice: '두 못이 서로 맞닿았으니, 군자는 벗들과 강론하고 도를 익힙니다.',
    score: 93,
    grade: '대길(大吉)',
    actionGuidance: '밝은 미소와 긍정적인 화법으로 사람들을 대하세요. 기쁨이 복을 부릅니다.',
    fortuneAspects: {
      wealth: '서비스업, 엔터테인먼트, 상담, 강연 등 입을 통한 수익이 대길합니다.',
      career: '동료들과 화기애애한 분위기 속에서 협업의 시너지를 발휘합니다.',
      love: '서로 바라보기만 해도 웃음이 터져 나오는 행복한 연애를 누립니다.',
      health: '구강, 치아, 인후 건강을 챙기고 밝은 마음으로 건강을 지키세요.',
    },
  },
  {
    num: 59,
    nameKr: '풍수환(風水渙)',
    nameHanja: '渙',
    upperKey: '손',
    lowerKey: '감',
    symbolMeaning: '봄바람이 불어 얼어붙은 강물을 흩뜨려 녹이듯 모든 막힘과 응어리가 흩어짐',
    judgment: '왕이 종묘에 이르며, 큰 내를 건넘에 이로우니 바르게 함에 길하리라.',
    imageAdvice: '바람이 물 위로 부니, 선왕은 상제를 받들고 사당을 세웁니다.',
    score: 90,
    grade: '길(吉)',
    actionGuidance: '오랜 갈등이나 응어리를 훌훌 털어버리세요. 막혔던 운로가 활짝 열립니다.',
    fortuneAspects: {
      wealth: '돈이 흩어지는 듯하나 더 큰 투자를 위한 물꼬가 트입니다.',
      career: '해외 진출, 유학, 타지역 이전 등 넓은 물로 나아가기에 최적입니다.',
      love: '서운했던 과거의 앙금을 깨끗이 용서하고 새로운 사랑을 시작하세요.',
      health: '체내 어혈과 노폐물이 원활히 배출되고 혈액순환이 개선됩니다.',
    },
  },
  {
    num: 60,
    nameKr: '수택절(水澤節)',
    nameHanja: '節',
    upperKey: '감',
    lowerKey: '태',
    symbolMeaning: '대나무 마디처럼 못물이 넘치지 않도록 적절하게 분수를 지키는 절제의 미덕',
    judgment: '형통하니, 너무 가혹한 절제는 오래 지속하기 어려우니 알맞게 하라.',
    imageAdvice: '못 위에 물이 있으니, 군자는 수와 법도를 제정하여 덕행을 논합니다.',
    score: 86,
    grade: '길(吉)',
    actionGuidance: '과유불급입니다. 규칙과 분수를 지키되 지나치게 가혹하지 않도록 균형을 잡으세요.',
    fortuneAspects: {
      wealth: '정해진 예산 내에서 계획적인 지출을 실천하면 통장이 든든해집니다.',
      career: '규정 준수, 회계 감사, 품질 관리에 탁월한 성과를 거둡니다.',
      love: '서로에 대한 예의와 적절한 거리를 지킬 때 사랑이 오래갑니다.',
      health: '과음과 과식을 끊고 절주와 규칙적인 생활을 실천하세요.',
    },
  },
  {
    num: 61,
    nameKr: '풍택중부(風澤中孚)',
    nameHanja: '中孚',
    upperKey: '손',
    lowerKey: '태',
    symbolMeaning: '어미 새가 알을 품듯 마음속 깊은 신의가 돼지와 물고기까지 감동시킴',
    judgment: '미물까지 감동케 하니 길하며, 큰 내를 건넘에 이로우니라.',
    imageAdvice: '못 위에 바람이 있으니, 군자는 옥사를 너그럽게 하고 사형을 멈춥니다.',
    score: 96,
    grade: '대길(大吉)',
    actionGuidance: '진실된 신뢰와 정직함으로 승부하세요. 굳게 닫힌 상대의 마음도 활짝 열립니다.',
    fortuneAspects: {
      wealth: '신용을 바탕으로 한 대형 계약 체결과 안정적인 금융 신뢰를 확보합니다.',
      career: '진정성 있는 소통으로 클라이언트와 부하 직원들의 절대적인 지지를 얻습니다.',
      love: '마음과 영혼이 완벽히 일치하는 깊은 영적 교감의 사랑을 나눕니다.',
      health: '호흡이 편안해지고 심장 박동이 안정되며 심신이 평화롭습니다.',
    },
  },
  {
    num: 62,
    nameKr: '뇌산소과(小過)',
    nameHanja: '小過',
    upperKey: '진',
    lowerKey: '간',
    symbolMeaning: '새가 하늘 높이 날지 않고 낮게 날듯 작은 일에 조금 지나치게 조심함',
    judgment: '작은 일은 가하나 큰일은 불가하니, 새가 날아오르지 않고 낮게 낢이 길하다.',
    imageAdvice: '산 위에 우레가 있으니, 군자는 행동에 조금 지나치게 공손합니다.',
    score: 76,
    grade: '평(平)',
    actionGuidance: '큰 승부를 걸 때가 아닙니다. 작은 디테일을 꼼꼼하게 챙기며 낮게 엎드리세요.',
    fortuneAspects: {
      wealth: '무리한 대형 베팅을 피하고 잔돈과 푼돈을 아끼며 실속을 챙기세요.',
      career: '사소한 문서 오탈자나 계약 세부 조항을 두 번 세 번 검토하세요.',
      love: '말 한마디라도 조금 더 공손하고 조심스럽게 건네는 배려가 필요합니다.',
      health: '낙상 사고나 가벼운 염좌를 조심하고 계단을 오르내릴 때 주의하세요.',
    },
  },
  {
    num: 63,
    nameKr: '수화기제(水火旣濟)',
    nameHanja: '旣濟',
    upperKey: '감',
    lowerKey: '리',
    symbolMeaning: '물과 불이 완벽한 조화를 이루어 솥에 밥이 다 익듯 모든 목적을 이미 완성함',
    judgment: '처음에는 길하나 마침내는 어지러우니, 완성을 지키는 데 만전을 기하라.',
    imageAdvice: '물이 불 위에 있으니, 군자는 환란을 생각하여 미리 방비합니다.',
    score: 89,
    grade: '길(吉)',
    actionGuidance: '성공의 정점에 도달했습니다. 이제는 방심하지 말고 마무리를 지키는 수성에 집중할 때!',
    fortuneAspects: {
      wealth: '목표한 수익을 달성했으니 욕심내어 재투자하지 말고 수익을 확정 지으세요.',
      career: '프로젝트 완수를 축하하되 사후 관리와 보고서 작성을 꼼꼼히 하세요.',
      love: '완벽한 결혼과 결실에 도달했으니 권태기에 빠지지 않도록 노력하세요.',
      health: '수승화강(水昇火降)이 잘 이루어져 건강하나 방심하지 마세요.',
    },
  },
  {
    num: 64,
    nameKr: '화수미제(火水未濟)',
    nameHanja: '未濟',
    upperKey: '리',
    lowerKey: '감',
    symbolMeaning: '불은 위에 있고 물은 아래에 있어 아직 미완성이지만 무한한 가능성의 새출발',
    judgment: '어린 여우가 강을 다 건너려다 꼬리를 적시니, 끝은 곧 새로운 시작이니라.',
    imageAdvice: '불이 물 위에 있으니, 군자는 사물을 신중히 가려 제자리에 둡니다.',
    score: 85,
    grade: '길(吉)',
    actionGuidance: '미완성이란 곧 무한한 기회의 시작입니다. 희망을 품고 새로운 사이클을 여세요.',
    fortuneAspects: {
      wealth: '새로운 사업 투자와 다음 사이클의 자금 계획을 세우기에 아주 좋습니다.',
      career: '마지막 2%의 점검을 마치면 완전히 새로운 도약의 문이 열립니다.',
      love: '아직은 밀당의 줄다리기 단계이나 곧 결정적인 전환점을 맞이합니다.',
      health: '상열하한(上熱下寒)을 다스리고 족욕과 반신욕으로 기운을 순환시키세요.',
    },
  },
];

/**
 * Maps 6 Yin/Yang lines to one of the 64 Hexagrams in King Wen sequence
 */
export function getHexagramFromLines(lines: ('yin' | 'yang')[]): HexagramData {
  // Lower trigram: lines[0], lines[1], lines[2]
  // Upper trigram: lines[3], lines[4], lines[5]
  const lowerLines = [lines[0], lines[1], lines[2]];
  const upperLines = [lines[3], lines[4], lines[5]];

  const lowerTrigram = Object.entries(EIGHT_TRIGRAMS).find(([_, info]) => 
    info.lines[0] === lowerLines[0] &&
    info.lines[1] === lowerLines[1] &&
    info.lines[2] === lowerLines[2]
  )?.[0] || '건';

  const upperTrigram = Object.entries(EIGHT_TRIGRAMS).find(([_, info]) => 
    info.lines[0] === upperLines[0] &&
    info.lines[1] === upperLines[1] &&
    info.lines[2] === upperLines[2]
  )?.[0] || '건';

  const found = ICHING_64_DATABASE.find(
    h => h.upperKey === upperTrigram && h.lowerKey === lowerTrigram
  );

  return found || ICHING_64_DATABASE[0];
}
